### ISSUE TITLE
Installation Instructions for stack

### ISSUE THREAD

**Issue by GetContented** [snapframework/snap-website#41]
Wondering if you'd consider adding installation instructions using stack

**Comment by gregorycollins** [comment]
We'll take a pull request, but personally I don't use it and don't have time to write this.

**Comment by mightybyte** [comment]
Also, this is the repo for the snapframework.com website.  We, the Snap developers, are the intended users...not the general public.  Since we don't use stack, adding that support doesn't really yield much value here.

**Comment by gregorycollins** [comment]
If people want to install snap via stack, I don't want to stop them either. Reiterate: we'll take a pull request

**Comment by GetContented** [comment]
:+1:  thanks.
