### ISSUE TITLE
Domain name expiration message

### ISSUE THREAD

**Issue by lexun** [snapframework/snap-website#48]
I'm getting the following message when I visit http://snapframework.com/

> This Domain Name Has Expired

![image](https://user-images.githubusercontent.com/1910143/30254153-fc7f663c-962f-11e7-99e2-d217a07f78d7.png)

**Comment by mightybyte** [comment]
Thanks for the heads-up.  We're aware of this issue.  Unfortunately we haven't yet been able to get a response from the person who has the domain registration.  In the meantime we have set up http://snapframework.io to point to the Snap website.

**Comment by jamessanders** [comment]
Hey sorry the domain was associated with an old account of mine on which the CC expired,  I have renewed the domain now so it should be back in business very soon.

**Comment by lexun** [comment]
Great, it seems to be back up now. I figured you were most likely aware, just wanted to make sure since I couldn't find an open issue about it.

**Comment by mightybyte** [comment]
@lexun Yes, thanks for the heads-up.
